version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 5.0.0
  - dependency-name: ts-jest
    versions:
    - 26.5.4
  - dependency-name: "@types/pino"
    versions:
    - 6.3.7
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: pino
    versions:
    - 6.11.0
    - 6.11.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
