name: CI - Build
on: [push]
jobs:
  build:
    name: Transpiles the code to JS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v1

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installs dependencies
        run: yarn install

      - name: Build Typescript
        run: yarn build
