name: Docker Build & Publish
description: Builds the Docker image and publishes it to GitHub registry

on: [release]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker_version: []

    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: ${{matrix.docker_version}}
          docker_channel: ${{matrix.docker_channel}}
      - name: Build Docker image
        run: docker build angeloanan/lyrics-finder/lyrics-finder:version
